### ISSUE TITLE
Allow other code-pages while reading SRT files

### ISSUE THREAD

**Issue by kim0** [deestan/srt2vtt#3]
Many srt files are not cp1252 or utf8 encoded. I think it would be pretty helpful to enable reading those using their native encodings

**Comment by deestan** [comment]
Makes sense.  Do you have any sample files for me to test with?

**Comment by kim0** [comment]
hmm try downloading this http://subscene.com/subtitles/game-of-thrones-fifth-season-2015/arabic/1130481 .. Any file in the zip should work

**Comment by deestan** [comment]
Thanks.  Do you know which encoding/codepage they're using?  I'm not familiar enough with Arabic to verify if I get it right or wrong.

**Comment by kim0** [comment]
Yeah, it's usually called cp1256 .. windows-1256 ..etc

**Comment by deestan** [comment]
Thanks again!

Can you confirm that the first few lines of file `Game.of.Thrones.S05E09.720p.HDTV.2CH.x265.HEVC-PSA.srt` are supposed to contain the following:

```
1
00:00:16,800 --> 00:00:19,500
<i><b>"كينغ لاندينج"</b></i>

2
00:00:30,066 --> 00:00:34,266
<i><b>"وينترفيل"</b></i>

3
00:00:47,203 --> 00:00:52,038
<i><b>"السُور"</b></i>

4
00:01:01,808 --> 00:01:05,008
<i><b>"برافوس"</b></i>
```

**Comment by deestan** [comment]
![skjermbilde](https://cloud.githubusercontent.com/assets/84091/8184512/1f94c47a-143f-11e5-9753-4e691ce4299a.PNG)

**Comment by kim0** [comment]
Indeed that looks like proper Arabic characters (although they're some place names "Winterville?" ) so not really conversation/words

**Comment by deestan** [comment]
"Winterfell" is a castle in GoT, so I assume this is correct.  Will be using it for the unit test case. :)

**Comment by kim0** [comment]
Cool! Thanks a lot
