### ISSUE TITLE
RFE: Allow changing output font size and bg color

### ISSUE THREAD

**Issue by kim0** [deestan/srt2vtt#4]

**Comment by deestan** [comment]
Please reopen with more details if still applicable.

What is the use case?  Change all fonts?  Some?  Based on original file data, or programatically?

**Comment by kim0** [comment]
Another project I care about (castnow) uses srt2vtt https://github.com/xat/castnow/search?utf8=%E2%9C%93&q=srt2vtt .. Now it does not support displaying fonts (bigger, yellow fg color, black bg outline/shadow...etc) bec my understanding is that those kind of things should be done in srt2vtt .. hence this PR .. so yes, only allow them programmatically .. Thanks!

**Comment by kim0** [comment]
@deestan Not really sure if you'll see my comment .. so mentioning you .. Thanks!

**Comment by deestan** [comment]
I get the comment, I'm just very very slow to reply sometimes. :)

The suggestion is interesting, but I will need a more exact use case before I can do anything.  I don't want to solve a problem that I don't have clearly in front of me, as that usually results in clunky and barely usable abstractions.

**Comment by kim0** [comment]
What about a clear definition as below:
1- Support programmatic setting of font size through API
2- Support programmatic setting of font foreground color through API

and that's all .. I hope that's clear enough. Otherwise, maybe we can engage @xat to mention more details than I can .. Thanks !

**Comment by deestan** [comment]
It'd like to know more details, please. :)

Currently, the transformation is done as stream in -> stream out, with no hooks into the different segments.  So, is it a way to set the same color and size of all text that is needed?  Or would callback hooks for each segment be the way to go?

A "this is the input file" and "this is the output I want" would be useful.  Let's see if @xat has any opinions.
